### ISSUE TITLE
Pass tags to go build?

### ISSUE THREAD

**Issue by dko1905** [nix-community/gomod2nix#109]
I've searched the previous issues for "build tags" and couldn't find anything.
I have a project with go-sqlite3, and I require the 'sqlite_math_functions' tag.
I usually add `--tags sqlite_math_functions` to `go build`, how do I do so
using buildGoApplication in my nix flake?

**Comment by peterldowns** [comment]
Have you tried the `tags` attribute? [The documentation[](https://github.com/nix-community/gomod2nix/blob/89cd0675b96775aa3ee86e7c0cf5bc238dd27976/docs/nix-reference.md) does not mention this attribute, but you can see how they're passed [if you look at `builder.nix`](https://github.com/nix-community/gomod2nix/blob/89cd0675b96775aa3ee86e7c0cf5bc238dd27976/builder/default.nix#L217).

**Comment by peterldowns** [comment]
Confirmed, `tags` works as expected. Every string you include in the `tags` array will be passed to the `go build` command:

```nix
default = pkgs.buildGoApplication {
  checkPhase = false;
  pname = "demo";
  version = "0.0.1";
  src = ./.;
  modules = ./gomod2nix.toml;
  tags = [
    "sqlite_math_functions"
  ];
};
```
```

**Comment by dko1905** [comment]
Hi, thanks. Any reason it isn't in the documentation?

**Comment by peterldowns** [comment]
Unfortunately I don't know, I'm not a maintainer. My guess is it's an honest oversight and that you could probably submit a PR to fix it if you'd like.

**Comment by jtcarnes** [comment]
I know this is a year old issue, but I had the problem. Small PR to add the documentation you mentioned @peterldowns to help the next guy.
