### ISSUE TITLE
overlay errors

### ISSUE THREAD

**Issue by Skarlett** [nix-community/gomod2nix#120]
using the flake, i receive the following error.
```
       error: cannot coerce null to a string

       at /nix/store/y6p51jza33989fck64faj0wyk2b1cp15-source/builder/default.nix:220:17:

          219|   buildGoApplication =
          220|     { modules ? pwd + "/gomod2nix.toml"
             |                 ^
          221|     , src ? pwd

```

If intentional, assert statements would clarify it.

**Comment by a-h** [comment]
I don't believe it's intentional, since the example in the README.md doesn't require the use of the `pwd` argument.

**Comment by a-h** [comment]
Not sure why you closed this.

This is a bug - `pwd` should either be defaulted to `./.`, or the documentation should be updated to state that it's required.
