### ISSUE TITLE
crash: `gomod2nix generate` not working with go 1.22 projects

### ISSUE THREAD

**Issue by kefniark** [nix-community/gomod2nix#151]
## Description
I got the same error in the past few days on migrating two different go project to the latest version `1.22`.

The nix file and `.buildGoApplication` still work as intended.
But the CLI which generate the `gomod2nix.toml` looks completely broken ... failing somewhere in a goroutine apparently. 

So with this issue, I can technically still dev and build with my nix flake, but I can't add any dependency anymore.
Does anyone has an idea or workaround?

## Logs
```sh
> gomod2nix generate
INFO[0000] Parsing go.mod                                modPath=go.mod
INFO[0000] Downloading dependencies                     
panic: error generating pkgs: exit status 1

goroutine 1 [running]:
github.com/nix-community/gomod2nix/internal/cmd.generateFunc(0xc000158900?, {0xbdaf60?, 0x4?, 0x85840b?})
        /build/source/internal/cmd/root.go:67 +0x40e
github.com/spf13/cobra.(*Command).execute(0xba6460, {0xbdaf60, 0x0, 0x0})
        /build/source/vendor/github.com/spf13/cobra/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0xba6180)
        /build/source/vendor/github.com/spf13/cobra/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /build/source/vendor/github.com/spf13/cobra/command.go:1039
github.com/nix-community/gomod2nix/internal/cmd.Execute()
        /build/source/internal/cmd/root.go:124 +0x1a
main.main()
        /build/source/main.go:6 +0xf
```

## Reproduction
Here is one of my PR which trigger the issue, I really just bumped the Go version from stable channel with `1.21` to unstable channel with `1.22`, it works with the first one and crash with the second.
Everything else is the same, even the version of gomod2nix

* [Upgrade to Go 1.22](https://github.com/kefniark/nix-go-template/pull/1/files)

```sh
nix develop .
gomod2nix generate
```

**Comment by jonpulsifer** [comment]
Adding the patch version allowed it to generate

```patch
@@ -1,6 +1,6 @@
 module github.com/my/app
 
-go 1.22
+go 1.22.1
```

**Comment by kefniark** [comment]
Wow indeed, I confirm it does the trick, looks like the patch version is now required.
Either `go 1.22.0` or `go 1.22.1` works, it only fail with `go 1.22`.
