### ISSUE TITLE
Is the default overlay meant to be for the Apple silicon?

### ISSUE THREAD

**Issue by shadowrylander** [nix-community/gomod2nix#84]
Hello!

As in the title; it seems that older channels cannot be used with the current overlay, even the latest stable nixos channel `nixos-22.05`, as its version of the `darwin` group does not currently have the `apple_sdk_11_0` pkgs, and therefore cannot use its `callPackage` function. Was this intended?

Thank you kindly for the information!

**Comment by yihuang** [comment]
not intended, we can make it conditional I think, will you submit a PR?

**Comment by srhb** [comment]
@yihuang Sure, there it is ^, and thanks for clarifying. :)

**Comment by srhb** [comment]
@shadowrylander The fallback has been merged, if you're good with that, I think this can be closed. :)

**Comment by shadowrylander** [comment]
It works! Sorry for the delay; was testing other things and forgot! 😅 Thanks for the quick fix!
